disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - no_extension_access_modifier
  - object_literal
  - type_body_length
  - type_name

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - empty_count
  - empty_enum_arguments
  - empty_string
  - fatal_error_message
  - file_header
  - first_where
  - force_cast
  - force_unwrapping
  - legacy_constructor
  - legacy_random
  - literal_expression_end_indentation
  - missing_docs
  - multiline_arguments
  - multiline_function_chains
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - strict_fileprivate
  - toggle_bool
  - trailing_whitespace
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.resolved
  - Package.swift
