disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - explicit_self
  - unused_import

custom_rules:
  sf_symbols_availability:
    name: "SF Symbols Availability"
    regex: 'Image\\(systemName:(?!.*#available)'
    message: "SF Symbols usage must be wrapped in an availability check"
    severity: error

  minimum_deployment_target:
    name: "Minimum Deployment Target"
    regex: '@available\\([^)]*iOS 1[0-3]\\.[0-9]'
    message: "iOS deployment target must be 14.0 or later"
    severity: error

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

included:
  - Sources
  - Tests

excluded:
  - .build
  - DemoApp

reporter: "xcode" 