name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

# Ensure we don't run on draft PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@v3
        with:
          args: --strict

  test:
    name: Build and Test
    runs-on: macos-15 # Latest macOS runner with Xcode 16.2
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      # Set up caching of Swift package dependencies
      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # Set up build cache
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      - name: Build and Test iOS
        run: |
          xcodebuild test \
            -scheme ColorKit \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 4 \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            -enableCodeCoverage YES \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Build and Test macOS
        run: |
          xcodebuild test \
            -scheme ColorKit \
            -destination 'platform=macOS,arch=arm64' \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 4 \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            -enableCodeCoverage YES \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure() # Upload even if tests fail
        with:
          name: test-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
          retention-days: 5
