name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    env:
      SWIFT_VERSION: swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-05-a
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Swift 6.0
      run: |
        curl -O https://download.swift.org/development/xcode/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-05-a/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-05-a-osx.pkg
        sudo installer -pkg swift-6.0-DEVELOPMENT-SNAPSHOT-2024-03-05-a-osx.pkg -target /
        
    - name: Set Swift 6.0
      run: |
        echo "TOOLCHAINS=swift" >> $GITHUB_ENV
        
    - name: Verify Swift Version
      run: swift --version
        
    - name: Build
      run: |
        swift package reset
        swift build
          
    - name: Test
      run: |
        swift test
          
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict 